- name: ollama deployment
  hosts: ollama
  roles:
  - common
  - ollama
  become: yes
  become_exe: /usr/bin/ssh
  become_flags: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -l root
    -p 222 127.0.0.1
  become_user: ''

